# Generated by Django 3.1.6 on 2021-02-11 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SensorData",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("sensor_type", models.CharField(max_length=100)),
                ("unit", models.CharField(max_length=100)),
                ("range_l", models.FloatField()),
                ("range_u", models.FloatField()),
                ("xid", models.CharField(max_length=100)),
                ("box_id", models.CharField(max_length=100)),
                ("longitude", models.FloatField()),
                ("latitude", models.FloatField()),
                ("reading", models.FloatField()),
                ("reading_ts", models.CharField(max_length=100)),
            ],
        ),
    ]
